$("#button1").click(function(){
    const str0 = $("#info-0").val();
    const str1 = $("#info-1").val();
    const str2 = $("#info-2").val();
    const str3 = $("#info-3").val();
    const str4 = $("#info-4").val();
    const str5 = $("#info-5").val();
    const str6 = $("#info-6").val();
    const str7 = $("#info-7").val();
    const str8 = $("#info-8").val();
    const str9 = $("#info-9").val();
    const str10 = $('input:radio[name="position"]:checked').val();
    const str11 = $('input:radio[name="font-type"]:checked').val();
    localStorage.setItem('company-name', str0);
    localStorage.setItem('postal-code1', str1);
    localStorage.setItem('postal-code2', str2);
    localStorage.setItem('address', str3);
    localStorage.setItem('telephone-number', str4);
    localStorage.setItem('fax-number', str5);
    localStorage.setItem('mail', str6);
    localStorage.setItem('url', str7);
    localStorage.setItem('catchcopy', str8);
    localStorage.setItem('other', str9);
    localStorage.setItem('position', str10);
    localStorage.setItem('font-type', str11);
});

window.onload = function(){
    var company_name = localStorage.getItem('company-name');
    var postal_code1 = localStorage.getItem('postal-code1');
    var postal_code2 = localStorage.getItem('postal-code2');
    var address = localStorage.getItem('address');
    var telephone_number = localStorage.getItem('telephone-number');
    var fax_number = localStorage.getItem('fax-number');
    var mail = localStorage.getItem('mail');
    var url = localStorage.getItem('url');
    var catchcopy = localStorage.getItem('catchcopy');
    var other = localStorage.getItem('other');
    var position = localStorage.getItem('position');
    var font_type = localStorage.getItem('font-type');
    $("#confirm-0").text(company_name);
    $("#confirm-1").text(postal_code1);
    $("#confirm-2").text(postal_code2);
    $("#confirm-3").text(address);
    $("#confirm-4").text(telephone_number);
    $("#confirm-5").text(fax_number);
    $("#confirm-6").text(mail);
    $("#confirm-7").text(url);
    $("#confirm-8").text(catchcopy);
    $("#confirm-9").text(other);
    $("#confirm-10").text(position);
    $("#confirm-11").text(font_type);
};